services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/var/www/html
volumes:
  db_data:
